// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGCOASZHNi68s68qHZpBUoObe9md5TdA4',
    appId: '1:948057126066:web:b02614d517576a7e6785ab',
    messagingSenderId: '948057126066',
    projectId: 'bus-karo-e60c0',
    authDomain: 'bus-karo-e60c0.firebaseapp.com',
    storageBucket: 'bus-karo-e60c0.firebasestorage.app',
    measurementId: 'G-C1C4VSZ3EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkeFILJ3eFhG1yXcGLP99o0W66n9qbvjQ',
    appId: '1:948057126066:android:d5f063adcffbe81f6785ab',
    messagingSenderId: '948057126066',
    projectId: 'bus-karo-e60c0',
    storageBucket: 'bus-karo-e60c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGfEZI5CFyNIHCKJtLrJiVLGxRczg8nqs',
    appId: '1:948057126066:ios:47ca508d7df49c116785ab',
    messagingSenderId: '948057126066',
    projectId: 'bus-karo-e60c0',
    storageBucket: 'bus-karo-e60c0.firebasestorage.app',
    iosBundleId: 'com.example.busKaro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGfEZI5CFyNIHCKJtLrJiVLGxRczg8nqs',
    appId: '1:948057126066:ios:47ca508d7df49c116785ab',
    messagingSenderId: '948057126066',
    projectId: 'bus-karo-e60c0',
    storageBucket: 'bus-karo-e60c0.firebasestorage.app',
    iosBundleId: 'com.example.busKaro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGCOASZHNi68s68qHZpBUoObe9md5TdA4',
    appId: '1:948057126066:web:099c384bf34949836785ab',
    messagingSenderId: '948057126066',
    projectId: 'bus-karo-e60c0',
    authDomain: 'bus-karo-e60c0.firebaseapp.com',
    storageBucket: 'bus-karo-e60c0.firebasestorage.app',
    measurementId: 'G-FCMF9ZGXH3',
  );
}
